// messages constants
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_ERROR = 'CREATE_MESSAGE_ERROR';
export const SET_MESSAGES = 'SET_MESSAGES';

// notification constants
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const SET_ACTIVE_NOTIFICATION = 'SET_ACTIVE_NOTIFICATION';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

// room constants
export const CREATE_ROOM = 'CREATE_ROOM';
export const INVITE_USERS_TO_ROOM = 'INVITE_USERS_TO_ROOM';
export const JOIN_ROOM_STREAM = 'JOIN_ROOM_STREAM';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const LEAVE_ROOM_STREAM = 'LEAVE_ROOM_STREAM';
export const RETRY_INVITATIONS = 'RETRY_INVITATIONS';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const SET_ROOMS = 'SET_ROOMS';
export const ROOM_ERROR = 'ROOM_ERROR';

// rtc constants
export const ADD_REMOTE_STREAM = 'ADD_REMOTE_STREAM';
export const GET_LOCAL_STREAM = 'GET_LOCAL_STREAM';
export const LOCAL_STREAM_ERROR = 'LOCAL_STREAM_ERROR';
export const REMOVE_REMOTE_STREAM = 'REMOVE_REMOTE_STREAM';
export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const STOP_LOCAL_STREAM = 'STOP_LOCAL_STREAM';
export const TOGGLE_LOCAL_AUDIO = 'TOGGLE_LOCAL_AUDIO';
export const TOGGLE_LOCAL_VIDEO = 'TOGGLE_LOCAL_VIDEO';
export const TOGGLE_REMOTE_AUDIO = 'TOGGLE_REMOTE_AUDIO';
export const UPDATE_REMOTE_STREAM = 'UPDATE_REMOTE_STREAM';

// users constants
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const CLEAR_AVAILABLE_USERS = 'CLEAR_AVAILABLE_USERS';
export const GET_AVAILABLE_USERS = 'GET_AVAILABLE_USERS';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_AS_GUEST = 'LOGIN_AS_GUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_PASSWORD = 'LOGIN_WITH_PASSWORD';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const SET_USERS = 'SET_USERS';
export const UPDATE_PROFILE_NAME = 'UPDATE_PROFILE_NAME';
